name: Build Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

env:
  EXE_NAME: w3s

jobs:
  Build_Win:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: cargo build -r

      - name: Upload traget bin
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: target/release/${{ env.EXE_NAME }}.exe


  Build_MacOS:
    runs-on: macos-11
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          rustup target add aarch64-apple-darwin
          cargo build -r
          cargo build -r --target aarch64-apple-darwin
          lipo -create -output ./${{ env.EXE_NAME }} ./target/release/${{ env.EXE_NAME }} ./target/aarch64-apple-darwin/release/${{ env.EXE_NAME }}

      - name: Upload traget bin
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./${{ env.EXE_NAME }}


  Build_Linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile
        run: cargo build -r

      - name: Upload traget bin
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: target/release/${{ env.EXE_NAME }}